app1/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_customer/', views.CreateCustomer.as_view(), name='create_customer'),
    path('add_file/', views.AddFile.as_view(), name='add_file'),
    path('filter', views.FilterView.as_view(), name='filter'),
    ####
    path('success_customer/', views.success_customer, name='success_customer'),
    path('success_file/', views.success_file, name='success_file'),
    path('results/', views.results, name='results')
]

reto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls'), name='reto'),
]

app1/models.py
import uuid
from django.db import models
from .choices import CustomerChoices, UploadChoices, SendChoices
from .utils.file_validation import validation


class Customers(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=45)
    parser = models.CharField(max_length=25, choices=CustomerChoices.CHOICES, null=False)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class FileParser(models.Model):
    id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customers, null=False, on_delete=models.CASCADE)
    emailID = models.UUIDField(default=uuid.uuid4)
    emailDate = models.DateTimeField()
    parse = models.CharField(max_length=25, null=False)
    options = models.CharField(max_length=25, choices=UploadChoices.CHOICES, null=False)
    send = models.CharField(max_length=10, choices=SendChoices.CHOICES, null=False)
    file = models.FileField(null=False, validators=[validation])
    created_at = models.DateTimeField()

    def __str__(self):
        return f"Customer: {self.customer.name} - EmailID: {self.emailID}"

app1/forms.py
from .models import Customers, FileParser
from django import forms


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customers

        fields = [
            'name',
            'parser',
        ]

        labels = {
            'name': 'Name',
            'parser': 'Parser',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'parser': forms.Select(attrs={'class': 'form-control'}),
        }


class FileParserForm(forms.ModelForm):
    class Meta:
        model = FileParser
        fields = [
            'customer',
            'emailID',
            'emailDate',
            'options',
            'send',
            'file',
            'created_at'
        ]

        labels = {
            'customer': 'Customer',
            'emailID': 'Email id',
            'emailDate': 'Email Date',
            'options': 'Option',
            'send': 'Send',
            'file': 'File',
            'created_at': 'Create at'
        }

        widgets = {
            'customer': forms.Select(attrs={'class': 'form-control'}),
            'emailID': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'true'}),
            'emailDate': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date'}),
            'options': forms.Select(attrs={'class': 'form-control'}),
            'send': forms.Select(attrs={'class': 'form-control'}),
            'file': forms.ClearableFileInput(attrs={'multiple': True}),
            'created_at': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date'})
        }

app1/views.py
# Create your views here.
import datetime
import pandas
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import CreateView, ListView
from .models import Customers, FileParser
from .forms import CustomerForm, FileParserForm
import uuid


def index(request):
    return render(request, 'index.html')


def success_customer(request):
    return render(request, 'success/success_customer.html')


def success_file(request):
    return render(request, 'success/success_file.html')


def results(request):
    return render(request, 'success/results.html')


class CreateCustomer(CreateView):
    model = Customers
    template_name = 'customer.html'
    form_class = CustomerForm
    success_url = reverse_lazy('success_customer')


class AddFile(CreateView):
    model = FileParser
    template_name = 'addfile.html'
    form_class = FileParserForm
    success_url = reverse_lazy('success_file')


class FilterView(View):

    def __init__(self):
        self.template_name = '../templates/filter.html'
        self.customers = Customers.objects.all()

    def get(self, request):
        return render(request, self.template_name, {'customers': self.customers})

    def post(self, request):
        filter = str(self.request.POST['filter_by'])
        if filter == 'Email_date':
            if FileParser.objects.filter(emailDate__gte=request.POST['date_initial'],
                                         emailDate__lte=request.POST['finish_date'], customer=request.POST['customer']):
                type = []
                create_date = []
                customer = []
                sent = []
                list = []
                info = FileParser.objects.filter(customer=self.request.POST['customer'])
                for inf in info:
                    type.append(str(inf.file))
                    create_date.append(str(inf.created_at))
                    customer.append(inf.customer.name)
                    sent.append(inf.send)
                for i in range(0, len(info)):
                    list.append([type[i], create_date[i], customer[i], sent[i]])
                df = pandas.DataFrame({'type': type, 'create_at ': create_date, 'customer': customer, 'sended': sent})
                link = f'media/informe-{str(uuid.uuid4().hex)}.xlsx'
                writer = pandas.ExcelWriter(link, engine='xlsxwriter')
                df.to_excel(writer, sheet_name='Sheet1')
                writer.save()
                context = {'list': list, 'link': link}
                return render(request, "success/results.html", context)
            else:
                return redirect('index')

        else:
            if FileParser.objects.filter(created_at__gte=request.POST['date_initial'],
                                         created_at__lte=request.POST['finish_date'],
                                         customer=request.POST['customer']):
                type = []
                create_date = []
                customer = []
                sent = []
                list = []
                info = FileParser.objects.filter(id=self.request.POST['customer'])
                for inf in info:
                    type.append(str(inf.file))
                    create_date.append(str(inf.created_at))
                    customer.append(inf.customer.name)
                    sent.append(inf.send)
                for i in range(0, len(info)):
                    list.append([type[i], create_date[i], customer[i], sent[i]])
                df = pandas.DataFrame({'type': type, 'create_at ': create_date, 'customer': customer, 'sended': sent})
                link = f'media/informe{datetime.datetime.now()}.xlsx'
                writer = pandas.ExcelWriter(link, engine='xlsxwriter')
                df.to_excel(writer, sheet_name='Sheet1')
                writer.save()
                context = {'list': list, 'link': link}
                return render(request, "success/results.html", context)
            else:
                return redirect('index')

templates/views.py
from django.shortcuts import render
from apps.exporterimporter_app.models import FileParser
from .forms import *

# Create your views here.
from django.views.generic import CreateView


def index(request):
    return render(request, 'index.html')


# class Exporter(CreateView):
#     model = FileParser
#     template_name = 'exporter.html'
#     form_class = FileParserForm

templates/addfile.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Add file{% endblock %}

<body>
{% block content %}
    <div class="view full-page-intro"
         style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/78.jpg'); background-repeat: no-repeat; background-size: cover; height: 1200px;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="container">
                <!--Grid row-->
                <!--Grid row-->
                <div class="row wow fadeIn col-xs-12">

                    <!--Grid column-->
                    <div class="col-md-6 mb-4" style="margin-left: auto;margin-right: auto;">

                        <!--Card-->
                        <div class="card" style="height: 950px;">

                            <!--Card content-->
                            <div class="card-body">

                                <!-- Form -->
                                <form enctype="multipart/form-data" method="post">
                                    {% csrf_token %}
                                    {{ form.errors }}
                                    <!-- Heading -->
                                    <h3 class="dark-grey-text text-center">
                                        <strong>Document Exporter Reporter</strong>
                                    </h3>
                                    <hr>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i>
                                        <label for="id_customer">{{ form.customer.label }}</label><br><br>
                                        {{ form.customer }}

                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i>
                                        <label for="id_emailID">{{ form.emailID.label }}</label><br><br>
                                        {{ form.emailID }}

                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i><br>
                                        <label for="id_emailDate">{{ form.emailDate.label }}</label><br>
                                        {{ form.emailDate }}
                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i><br>
                                        <label for="id_options">{{ form.options.label }}</label><br>
                                        {{ form.options }}
                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i><br>
                                        <label for="id_send">{{ form.send.label }}</label><br>
                                        {{ form.send }}
                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i><br>
                                        <label for="id_file">{{ form.file.label }}</label><br>
                                        {{ form.file }}
                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i><br>
                                        <label for="id_created_at">{{ form.created_at.label }}</label><br>
                                        {{ form.created_at }}
                                    </div>


                                    <div class="text-center">
                                        <button class="btn btn-indigo" type="submit">Send</button>
                                    </div>

                                </form>
                                <!-- Form -->

                            </div>

                        </div>
                        <!--/.Card-->

                    </div>
                    <!--Grid column-->


                </div>
                <!--Grid row-->
                <center>
                    <a class="btn btn-lg btn-primary text-uppercase" href="{% url 'index' %}">
                        <i class="fas fa-backward mr-2"></i>Index
                    </a>
                </center>
            </div>
            <!-- Content -->

        </div>

    </div>
{% endblock %}
</body>

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %} Exporter Importer {% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'plantilla/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'plantilla/css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'plantilla/css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'plantilla/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <style type="text/css">
        html,
        body,
        header,
        .view {
            height: 100%;
        }

        @media (max-width: 740px) {
            html,
            body,
            header,
            .view {
                height: 1000px;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {
            html,
            body,
            header,
            .view {
                height: 650px;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {
            .navbar:not(.top-nav-collapse) {
                background: #1C2331 !important;
            }
        }
    </style>
</head>

<body>

<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand" href="#" target="#_blank">
            <strong>Reports</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">

            </ul>

        </div>

    </div>
</nav>
<!-- Navbar -->

<!-- Navbar -->

<!-- Full Page Intro -->
{% block content %}


{% endblock %}
<!--Footer-->
<footer class="page-footer text-center font-small wow fadeIn">

    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="https://LSV-TECH.COM" target="_blank"> LSV TECH </a>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'plantilla/js/jquery-3.4.0.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'plantilla/js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'plantilla/js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'plantilla/js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>
</body>

</html>

templates/customer.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Exporter{% endblock %}

<body>
{% block content %}
    <div class="view full-page-intro"
         style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/78.jpg'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="container">
                <!--Grid row-->
                <!--Grid row-->
                <div class="row wow fadeIn col-xs-12">

                    <!--Grid column-->
                    <div class="col-md-6 mb-4" style="margin-left: auto;margin-right: auto;">

                        <!--Card-->
                        <div class="card">

                            <!--Card content-->
                            <div class="card-body">

                                <!-- Form -->
                                <form method="post">
                                    {% csrf_token %}
                                    <!-- Heading -->
                                    <h3 class="dark-grey-text text-center">
                                        <strong>Document Exporter Reporter</strong>
                                    </h3>
                                    <hr>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i>
                                        <label for="id_name">{{ form.name.label }}</label><br>
                                        {{ form.name }}

                                    </div>
                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i><br>
                                        <label for="id_parser">{{ form.parser.label }}</label><br>
                                        {{ form.parser }}
                                    </div>

                                    <div class="text-center">
                                        <button class="btn btn-indigo" type="submit">Send</button>
                                    </div>

                                </form>
                                <!-- Form -->

                            </div>

                        </div>
                        <!--/.Card-->

                    </div>
                    <!--Grid column-->


                </div>
                <!--Grid row-->
                <center>
                    <a class="btn btn-lg btn-primary text-uppercase" href="{% url 'index' %}">
                        <i class="fas fa-backward mr-2"></i>Index
                    </a>
                </center>
            </div>
            <!-- Content -->

        </div>

    </div>

{% endblock %}
</body>

templates/filter.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Filter{% endblock %}

<body>
{% block content %}
    <div class="view full-page-intro"
         style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/78.jpg'); background-repeat: no-repeat; background-size: cover; height: 952px;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="container">
                <!--Grid row-->
                <!--Grid row-->
                <div class="row wow fadeIn col-xs-12">

                    <!--Grid column-->
                    <div class="col-md-6 mb-4" style="margin-left: auto;margin-right: auto;">

                        <!--Card-->
                        <div class="card" style="height: 695px;">

                            <!--Card content-->
                            <div class="card-body">

                                <!-- Form -->
                                <form method="post">
                                    {% csrf_token %}
                                    <!-- Heading -->
                                    <h3 class="dark-grey-text text-center">
                                        <strong>Document Exporter Reporter</strong>
                                    </h3>
                                    <hr>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i>
                                        <label for="customer">Customer</label><br><br>
                                        <select id="customer" name="customer">
                                            {% if customers %}
                                                <option selected="-----">-----</option>
                                                {% for customer in customers %}
                                                    <option value={{ customer.id }}>{{ customer.name }}</option>
                                                {% endfor %}
                                            {% else %}
                                                <option value="Please back to add a customer">Please back to add a
                                                    customer
                                                </option>
                                            {% endif %}
                                        </select>

                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i>
                                        <label for="filter_by">Filter by</label><br><br>
                                        <select id="filter_by" name="filter_by">
                                            <option selected="-----">-----</option>
                                            <option value="Email_date">Email_date</option>
                                            <option value="Customer_date">Customer_date</option>
                                        </select>

                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i>
                                        <label for="date_initial">Date initial</label><br><br>
                                        <input type = 'date' name = 'date_initial'>

                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i>
                                        <label for="finish_date">Finish date</label><br><br>
                                        <input type = 'date' name = 'finish_date'>
                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-address-card prefix grey-text"></i>
                                        <label for="status">Status send</label><br><br>
                                        <select id="status" name="status">
                                            <option selected="-----">-----</option>
                                            <option value="true">true</option>
                                            <option value="false">false</option>
                                        </select>
                                    </div><br>

                                    <div class="text-center">
                                        <button class="btn btn-indigo" type="submit">Send</button>
                                    </div>

                                </form>
                                <!-- Form -->

                            </div>

                        </div>
                        <!--/.Card-->

                    </div>
                    <!--Grid column-->


                </div>
                <!--Grid row-->
                <center>
                    <a class="btn btn-lg btn-primary text-uppercase" href="{% url 'index' %}">
                        <i class="fas fa-backward mr-2"></i>Index
                    </a>
                </center>
            </div>
            <!-- Content -->

        </div>

    </div>
{% endblock %}
</body>

templates/index.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %} Exporter importer {% endblock %}

<body>
{% block content %}
    <div class="view full-page-intro"
         style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/78.jpg'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="container">
                <!--Grid row-->
                <!--Grid row-->
                <div class="row wow fadeIn col-xs-12">

                    <!--Grid column-->
                    <div class="col-md-6 mb-4" style="margin-left: auto;margin-right: auto;">

                        <!--Card-->
                        <div class="card">

                            <!--Card content-->
                            <div class="card-body" style="padding-top: 103px;">

                                <div class="text-center">
                                    <a href="{% url 'create_customer' %}" class="btn btn-indigo" type="button">Create
                                        customer</a>
                                </div>

                                <div class="text-center">
                                    <a href="{% url 'add_file' %}" class="btn btn-indigo" type="button">Add file</a>
                                </div>

                                <div class="text-center">
                                    <a href="{% url 'filter' %}" class="btn btn-indigo" type="button">Filter</a>
                                </div>

                            </div>

                        </div>
                        <!--/.Card-->

                    </div>
                    <!--Grid column-->


                </div>
                <!--Grid row-->
            </div>
            <!-- Content -->

        </div>

    </div>
{% endblock %}
</body>

templates/success/results.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Results{% endblock %}
<body>

{% block content %}
    <div class="view full-page-intro"
         style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/78.jpg'); background-repeat: no-repeat; background-size: cover; height: 952px;">
        <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
            <div style="width: 80%">

                <div class="wrap-login100">
                    <div class="login100-form-title">
                        <h2 class="text-uppercase text-center text-white"><strong>Results</strong></h2>
                        <br>
                        <table id="MyTable" class="table table-dark table-striped table-hover text-center" border="1"
                               width="100%">
                            {% if list %}
                                <thead>
                                <td>Type</td>
                                <td>Create_at</td>
                                <td>Customer</td>
                                <td>Send</td>

                                </thead>
                                <tbody>
                                {% for object in list %}
                                    <tr>
                                        {% for i in object %}
                                            <td>{{ i }}</td>
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
{#                                <tr>#}
{#                                    <td colspan="4">#}
{#                                        <a href="{{ link }}" download="asd.xlsx" class="btn btn-primary">Download</a>#}
{#                                    </td>#}
{#                                </tr>#}
                                </tbody>
                            {% else %}
                                <h2 class="text-center text-white">No files</h2>
                            {% endif %}
                        </table>
                    </div>

                </div>
                <br>
                <a class="btn btn-lg btn-primary btn-block text-uppercase"
                   href="{% url 'index' %}">
                    <i class="fas fa-backward mr-2"></i>Index</a>

            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                    paging: false,
                    scrollY: 210,
                    select: true,
                    language: {
                        searchPlaceholder: "Search",
                        search: "",
                    }

                }
            );
        });
    </script>
{% endblock %}
</body>